name: Node.js CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test || echo "Tests are not defined, skipping..." 

      - name: Build Project
        run: npm run build || echo "Build step is not configured yet."

      - name: Deploy (Optional)
        if: success()
        run: echo "Deploy step can be added here."
